name: CI

# Запускать на пуши и PR в ветки main и fast_screen
on:
  push:
    branches:
      - main
      - fast_screen
  pull_request:
    branches:
      - main
      - fast_screen

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      # 1) Клонируем репу
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Кешируем pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Убедимся, что наш пакет установлен в editable-режиме
          pip install -e .

      # 5) Запускаем тесты
      - name: Run pytest
        run: pytest

      # 6) (Опционально) Запускаем линтер flake8
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .
